#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    flipSense,      sensorAnalog)
#pragma config(Sensor, in8,    gyroSense,      sensorAnalog)
#pragma config(Sensor, dgtl1,  noPlatLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  redALED,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  blueALED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  farFlagLED,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, platJumper,     sensorDigitalIn)
#pragma config(Sensor, dgtl11, nearFarJumper,  sensorDigitalIn)
#pragma config(Sensor, dgtl12, blueRedJumper,  sensorDigitalIn)
#pragma config(Sensor, I2C_1,  rightIME,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           right1,        tmotorVex393_MC29, PIDControl, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port3,           right2,        tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           right0,        tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           flipR,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           flipL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           left0,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           left2,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           left1,         tmotorVex393_MC29, PIDControl, driveLeft, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

// Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// Includes for PID control
#include "./libPID/NERD_PID.c"
#include "./libGyro/NERD_Gyro.c"

// Gyro stuff
float kP = 0.08;
float kD = 0.003;
Gyro gyro;
PID gyroPID;

// Driving PID
PID motorPositionPID;
PID keepStraightPID;

// Will possibly use
PID flipPID;

// Auton variables
bool isNearFlag;
bool isPlatform;
int turnDirection;
bool keepHolding;

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
    // Set bStopTasksBetweenModes to false if you want to keep user created tasks
    // running between Autonomous and Driver controlled modes. You will need to
    // manage all user created tasks if set to false.
    bStopTasksBetweenModes = true;

    // Reset just in case
    resetMotorEncoder(right1);
    resetMotorEncoder(left1);

    // Initialize motor slaves
    slaveMotor(right0, right1);
    slaveMotor(right2, right1);
    slaveMotor(left0, left1);
    slaveMotor(left2, left1);

    slaveMotor(flipL, flipR);

    // Initialize the gyro
    gyro_init(gyro, gyroSense, false);
    pidInit(gyroPID, kP, 0, kD);

    // Initialize driving straight PID
    pidInit(motorPositionPID, 0.005, 0, 0);
    pidInit(keepStraightPID, 0.01, 0, 0);

    // Initialize flipPID
    pidInit(flipPID, 0.1, 1, 0.01);
    keepHolding = false;

    // Choose auton program
    // Choose blue or red alliance
    if (SensorValue[blueRedJumper] == 1)
    {
        turnDirection = 1;
        SensorValue[blueALED] = 1;
    }
    else
    {
        turnDirection = -1;
        SensorValue[redALED] = 1;
    }

    // Choose if is near flag
    if (SensorValue[nearFarJumper] == 1)
        isNearFlag = true;
    else
    {
        isNearFlag = false;
        SensorValue[farFlagLED] = 1;
    }

    // Choose if doing platform
    if (SensorValue[platJumper] == 1)
    {
        isPlatform = true;
    }
    else
    {
        isPlatform = false;
        SensorValue[noPlatLED] = 1;
    }
}

void
holdFlipAngle(float fTarget)
{
    while (keepHolding)
    {
        // Get current position
        float fFlipAngle = SensorValue[flipSense];

        // Calculate the power and apply it
        float fPower = pidCalculate(flipPID, fTarget, fFlipAngle) * 127;
        motor[flipR] = fPower;

        wait1Msec(25);
    }
}
void
powerMotors(int leftPower, int rightPower)
{
    motor[left1] = leftPower;
    motor[right1] = rightPower;
}
void
powerMotors(int power)
{
    powerMotors(power, power);
}
void
goToPosition(long targetPosition, int maxSpeed)
{
    bool bAtTarget = false;
    long liAtTargetTime = nPgmTime;

    while (!bAtTarget)
    {
        float currentPositionR = getMotorEncoder(right1);
        float currentPositionL = getMotorEncoder(left1) + targetPosition / 70;

        /*
        float error = targetPosition - currentPositionR;
        float integral = motorPositionPID.sigma;
        float derivative = 0;

        long dTime = (nPgmTime - motorPositionPID.lastTime) * 0.001;

        if (dTime != 0)
            derivative = (currentPositionR - motorPositionPID.lastValue) / dTime;
            */
/*
        float error = currentPositionR - currentPositionL;
        float integral = keepStraightPID.sigma;
        float derivative = 0;

        long dTime = (nPgmTime - keepStraightPID.lastTime) * 0.001;

        if (dTime != 0)
            derivative = (currentPositionL - keepStraightPID.lastValue) / dTime;
*/
        // Calculate the output of the PID controller and output to drive motors
        float driveOutR = pidCalculate(motorPositionPID, targetPosition, currentPositionR) * maxSpeed;
        float driveOutL = driveOutR + pidCalculate(keepStraightPID, currentPositionR, currentPositionL) * 100;

        /*
        // Log on dataLog
        datalogDataGroupStart();
        datalogAddValue(0, error);
		datalogAddValue(1, integral);
		datalogAddValue(2, derivative);
		datalogAddValue(4, driveOutR);
		datalogAddValue(5, driveOutL);
        datalogDataGroupEnd();
*/
        powerMotors(driveOutR, driveOutR);

        // Stop the turn function when the position has been within 12 ticks of the desired encoder tick for 350ms
        if(abs(targetPosition - currentPositionR) > 12 || abs(targetPosition - currentPositionL) > 12)
            liAtTargetTime = nPgmTime;
        if (nPgmTime - liAtTargetTime > 350)
        {
            bAtTarget = true;
            powerMotors(0);
        }
    }
}
/**
* Drive straight a certain distance
* @param distance the specific encoder tick to travel to
* @param reset if motor encoder needs to be reset to 0 before the move
*/
void
driveStraight(long distance, bool reset)
{
    if (reset)
    {
        resetMotorEncoder(right1);
        resetMotorEncoder(left1);
    }

    goToPosition(distance, 100);
}
/**
* gyro turn to target angle
*
* @param fTarget target value of gyro turn (in degrees)
* @param fGyroAngle initial angle of gyro (in degrees)
* @param maxSpeed maximum motor power to use (up to 127)
*/
float
gyroTurn(float fTarget, float fGyroAngle, int maxSpeed)
{
    bool bAtGyro = false;
    long liAtTargetTime = nPgmTime;
    long liTimer = nPgmTime;

    while (!bAtGyro)
    {
        // Calculate the delta time from the last iteration of the loop
        float fDeltaTime = (float)(nPgmTime - liTimer) * 0.001;
        // Reset loop timer
        liTimer = nPgmTime;

        // Add on to current robot angle
        fGyroAngle += gyro_get_rate(gyro) * fDeltaTime;

        // Get variables for datalog
        //float error = fTarget - fGyroAngle;
        //float integral = gyroPID.sigma;
        //float derivative = 0;

        //long dTime = (nPgmTime - gyroPID.lastTime) * 0.001;
        //if (dTime != 0)
          //  derivative = (fGyroAngle - gyroPID.lastValue) / dTime;

        // Calculate the output of the PID controller and output to drive motors
        float driveOut = pidCalculate(gyroPID, fTarget, fGyroAngle) * maxSpeed;

        // Log on dataLog
        //datalogDataGroupStart();
        //datalogAddValue(0, error);
		//datalogAddValue(1, integral);
		//datalogAddValue(2, derivative);
		//datalogAddValue(4, driveOut);
        //datalogDataGroupEnd();

        powerMotors(-driveOut, driveOut);

        // Stop the turn function when the angle has been within 2 degrees of the desired angle for 350ms
        if(abs(fTarget - fGyroAngle) > 2)
            liAtTargetTime = nPgmTime;
        if (nPgmTime - liAtTargetTime > 350)
        {
            bAtGyro = true;
            powerMotors(0);
        }
    }
    // Reinitialize the PID constants to their original values in case they were changed
    pidInit(gyroPID, kP, 0, kD);
    return fGyroAngle;
}

/**
* Overloaded gyro turn for simpler use
* @param fTarget target angle to turn to (in degrees)
*/
float
gyroTurn(float fTarget)
{
    return gyroTurn(fTarget, 0, 65);
}
// Functions for the flipper
task raise()
{

    motor[flipR] = 30;
    waitUntil(SensorValue[flipSense] > 3000);
    motor[flipR] = 0;
    /*
    keepHolding = true;
    holdFlipAngle(3000);
    waitUntil(SensorValue[flipSense] > 3000);
    keepHolding = false;
    */

}
task returnDown()
{

    motor[flipR] = -30;
    waitUntil(SensorValue[flipSense] < 1200);
    motor[flipR] = 5;
    wait1Msec(100);
    motor[flipR] = 0;
    /*
    keepHolding = true;
    holdFlipAngle(1200);
    waitUntil(SensorValue[flipSense] < 1200);
    keepHolding = false;
    */
}
task flip()
{

    motor[flipR] = 100;
    waitUntil(SensorValue[flipSense] > 1400);
    motor[flipR] = 70;
    waitUntil(SensorValue[flipSense] > 1700);
    motor[flipR] = 0;
    /*
    keepHolding = true;
    holdFlipAngle(1700);
    waitUntil(SensorValue[flipSense] > 1700);
    keepHolding = false;
    */
}
task flipAndReturn()
{
    startTask(flip);
    wait1Msec(400);
    startTask(returnDown);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*---------------------------------------------------------------------------*/
void
autonNearFlagNoPlat()
{
    // Go backwards to hit 1st flag
    driveStraight(-2200, true);

    // Go forwards (line up with 1st cap)
    driveStraight(-1100, false);

    // Turn 90 deg (face 1st cap)
    gyroTurn(-90 * turnDirection);

    // Square up against wall
    motor[right1] = -60;
    motor[left1] = -60;

    // Lower flipper
    startTask(returnDown);
    wait1Msec(750);

    resetMotorEncoder(right1);
    resetMotorEncoder(left1);

    // Go forward to 1st cap
    motor[right1] = 85;
    motor[left1] = 85;

    waitUntil(getMotorEncoder(right1) > 800);

    // Flip 1st cap while still moving forward
    startTask(flip);
    wait1Msec(500);
    startTask(raise);

    // Travel to end to line up with 2nd flag
    driveStraight(1800, false);

    // Turn 90 deg (to line up backwards with 2nd flag)
    gyroTurn(90 * turnDirection);

    // Back up to square with wall and hit 2nd flag
    driveStraight(-1100, true);
    motor[right1] = -60;
    motor[left1] = -60;
    wait1Msec(750);

    // Lower flipper
    startTask(returnDown);

    // Go forward to 2nd tilted cap
    driveStraight(1800, true);

    // Sweep the floor to right to knock 2nd cap off ball
    float tempAngle = gyroTurn(-60 * turnDirection, 0, 80);
    // Then return to center
    gyroTurn(0, tempAngle, 55);

    // If we are not doing platform, stop everything
    if (!isPlatform)
    {
        return;
    }

    // Raise flipper to get out of the way
    startTask(raise);

    // Go forwards and center in tile to line up with starting alliance tile
    driveStraight(300, true);

    // Turn 90 deg to face alliance tile backwards
    gyroTurn(-90 * turnDirection);

    // Back up to square with wall
    driveStraight(-1900, true);
    motor[right1] = -60;
    motor[left1] = -60;
    wait1Msec(500);

    // Move up slightly to rotate
    driveStraight(200, true);

    // Turn 90 deg (on way to line up with alliance platform)
    gyroTurn(90 * turnDirection);

    // Move in line with alliance platform
    driveStraight(1000, true);

    // Turn 90 deg (face alliance platform)
    gyroTurn(-90 * turnDirection);

    // Square against alliance platform
    motor[right1] = 40;
    motor[left1] = 40;
    wait1Msec(1000);

    // Climb platform
    motor[right1] = 127;
    motor[left1] = 127;
    wait1Msec(2000);

    // Stop everything
    motor[right1] = 0;
    motor[left1] = 0;
}
void autonNearFlagPlat()
{
    // Go backwards to hit 1st flag
    driveStraight(-2200, true);

    // Go forwards to line up with alliance platform
    driveStraight(1100, false);

    // Turn 90 deg (face alliance platform)
    gyroTurn(-90 * turnDirection);

    // Square against alliance platform
    motor[right1] = 40;
    motor[left1] = 40;
    wait1Msec(1500);

    // Climb platform
    motor[right1] = 127;
    motor[left1] = 127;
    wait1Msec(2000);

    // Stop everything
    motor[right1] = 0;
    motor[left1] = 0;
}
void
autonFarFlagPlat()
{
    // Move in line with alliance platform
    driveStraight(1100, true);

    // Turn 90 deg (face alliance platform)
    gyroTurn(90 * turnDirection);

    // Square against alliance platform
    motor[right1] = 40;
    motor[left1] = 40;
    wait1Msec(1500);

    // Climb platform
    motor[right1] = 127;
    motor[left1] = 127;
    wait1Msec(2000);

    // Stop everything
    motor[right1] = 0;
    motor[left1] = 0;
}
void
autonFarFlagNoPlat()
{

}
task autonomous()
{
    // Enable PID Control
    nMotorPIDSpeedCtrl[right1] = RegSpeed;
    nMotorPIDSpeedCtrl[left1] = RegSpeed;

    if (isNearFlag)
    {
        if (isPlatform)
            autonNearFlagPlat();
        else
            autonNearFlagNoPlat();
    }
    else
    {
        if (isPlatform)
            autonFarFlagPlat();
        else
            autonFarFlagNoPlat();
    }
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*---------------------------------------------------------------------------*/
void test()
{
    driveStraight(3000, true);
}
task usercontrol()
{
    test();
    //autonNearFlagPlat();

    // Remove PID Control for better driving
    nMotorPIDSpeedCtrl[right1] = RegIdle;
    nMotorPIDSpeedCtrl[left1] = RegIdle;

    while (true)
    {
        // Right motor
        motor[right1] =  vexRT[Ch2];

        // Left motor
        motor[left1] = vexRT[Ch3];

        // Kill flipper
        if (vexRT[Btn8U] == 1)
        {
            stopTask(returnDown);
            stopTask(flip);
            stopTask(flipAndReturn);
            stopTask(raise);
            keepHolding = false;

            motor[flipR] = 0;
        }
        // Flip and Return flipper
        if (vexRT[Btn6U] == 1)
            startTask(flipAndReturn);
        // Lower flipper
        if (vexRT[Btn6D] == 1)
            startTask(returnDown);
        // Raise flipper
        if (vexRT[Btn8D] == 1)
            startTask(raise);
    }
}
